org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.10
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

mod_id=ironcasting
mod_name=IronCasting
mod_license=MIT
mod_version=0.0.2
mod_group_id=pub.pigeon.yggdyy.ironcasting
mod_authors=yggdyy_
mod_description=Cast ISS spells in Hexcasting form.
hexcastingVersion=0.11.2-pre-702
patchouliVersion=80-FORGE
inline_version = 1.20.1-1.2.2-12